### ISSUE TITLE
output video

### ISSUE THREAD

**Issue by ChethanN01** [yjh0410/YOWOv2#13]
Team,

how do i get output videos?
i am seeing set of images when i do inference,

**Comment by yjh0410** [comment]
@ChethanN01 If you would like to detect videos, please run the `demo.py` file and refer to the README file for the command. When running the `demo.py` file to detect actions in a video, the results will be saved in the `det_results` folder in the format of the video. Please refer to the source code of `demo.py` for more details.

**Comment by ChethanN01** [comment]
closed
