### ISSUE TITLE
recognition problem

### ISSUE THREAD

**Issue by snehashis1997** [yjh0410/YOWOv2#2]
is there any way so that I can integrate yowov2 into my current yolox detector module? take the box from yolox head, pass it to the yowov2 classification part, and classify that particular object

**Comment by yjh0410** [comment]
@snehashis1997  YOWOv2, trained on AVA, can simultaneously locate the person in the current frame and identify the actions end-to-end. In my opinion, it seems that it may not be appropriate to assign the location person's bbox given by YOLOX head to YOWOv2 for classification. However, in my experience, YOWOv2 sometimes gives false positive predictions. For example, there are no people in some frames, but YOWOv2 still detects the target. Perhaps you can use YOLOX's head to suppress this false positive prediction. On the other hand, joint training of YOWOv2 and YOLOX to fully utilize YOLOX's powerful positioning capabilities may be a valuable way.

**Comment by snehashis1997** [comment]
Thank you for your valuable response. How about using blank background images during training? as of now, I do not think it is possible. How to do that.

**Comment by snehashis1997** [comment]
Thank you for your valuable response. How about using blank background images during training? as of now, I do not think it is possible. How to do that.

**Comment by tiamo405** [comment]
> Thank you for your valuable response. How about using blank background images during training? as of now, I do not think it is possible. How to do that.

det_conf = float(bbox[4]) is the probability of being human?
