### ISSUE TITLE
trainlist.txt内容和训练中的box

### ISSUE THREAD

**Issue by whisper233** [yjh0410/YOWOv2#24]
有两点不明白的地方请教作者，我说的啰嗦一点，希望能表达清楚我的疑惑，两个问题：
1）trainlist.txt中每行的信息是某视频中某一帧文件（图像）的项相对路径，看代码是根据某一帧去找对应的视频再取其中的16帧作为训练数据，为什么不是以视频为单位去选数据？
2）一个视频，动作是变化的，每一帧的动作框都在变化，为什么在训练的时候一个视频的框只用一组[x1, y1, x2, y2]框去表示GT呢，这个框的个数不应该是帧数嘛，刚入这个方向，求大佬指点。

**Comment by 121649982** [comment]
它是稀疏标注的。你训练出来了吗
